# Generated by Django 4.1.7 on 2023-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('festivals', models.CharField(max_length=100)),
                ('secret_spot', models.CharField(max_length=100)),
                ('todo', models.CharField(max_length=100)),
            ],
        ),
    ]
