# Generated by Django 4.1.7 on 2023-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_tripdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='trip_itinerary',
            field=models.TextField(default='this is a prompt'),
            preserve_default=False,
        ),
    ]
